name: Setup
description: Setup CI environment
runs:
  using: composite
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Install CI tools
      shell: bash
      run: nix profile install .#ci
    - name: Enable corepack
      shell: bash
      run: |
        mkdir -p "$HOME/.local/bin"
        corepack enable --install-directory "$HOME/.local/bin"
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
    - name: Cache pnpm store
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ~/.local/share/pnpm/store
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-pnpm-store-
