import js from "@eslint/js";
import tseslint from "@typescript-eslint/eslint-plugin";
import vitest from "@vitest/eslint-plugin";
import importPlugin from "eslint-plugin-import";
import jsdocPlugin from "eslint-plugin-jsdoc";
import promise from "eslint-plugin-promise";
import unicorn from "eslint-plugin-unicorn";
import { pluginsToRulesDTS } from "eslint-typegen/core";
import { execFileSync } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.resolve(__dirname, "../src/oxlint");

type RuleEntry = unknown;
type RuleMap = Record<string, RuleEntry>;

const renamePrefix = (rules: RuleMap, from: string, to: string): RuleMap => {
  const out: RuleMap = {};
  for (const [name, value] of Object.entries(rules)) {
    if (from === "" && !name.includes("/")) {
      out[to ? `${to}/${name}` : name] = value;
    } else if (from && name.startsWith(`${from}/`)) {
      out[`${to}/${name.slice(from.length + 1)}`] = value;
    } else {
      out[name] = value;
    }
  }
  return out;
};

const tsEslintRecommendedOverrides = (tseslint.configs["eslint-recommended"]?.overrides?.[0]
  ?.rules ?? {}) as RuleMap;

const sources: Array<{ from: string; rules: RuleMap; to: string }> = [
  { from: "", rules: js.configs.recommended.rules, to: "" },
  {
    from: "import",
    rules: importPlugin.configs.recommended.rules as RuleMap,
    to: "import",
  },
  {
    from: "jsdoc",
    rules: jsdocPlugin.configs["flat/recommended"].rules as RuleMap,
    to: "jsdoc",
  },
  {
    from: "promise",
    rules: promise.configs["flat/recommended"]?.rules ?? {},
    to: "promise",
  },
  { from: "", rules: tsEslintRecommendedOverrides, to: "" },
  {
    from: "@typescript-eslint",
    rules: tseslint.configs["strict-type-checked"]?.rules ?? {},
    to: "typescript",
  },
  {
    from: "unicorn",
    rules: unicorn.configs.recommended.rules as RuleMap,
    to: "unicorn",
  },
  {
    from: "vitest",
    rules: vitest.configs.recommended.rules,
    to: "vitest",
  },
];

const recommended: RuleMap = {};
for (const { from, to, rules } of sources) {
  Object.assign(recommended, renamePrefix(rules, from, to));
}

const require = createRequire(import.meta.url);
const oxlintPkgPath = require.resolve("oxlint/package.json");
const oxlintDtsPath = path.resolve(path.dirname(oxlintPkgPath), "dist/index.d.ts");
const oxlintDts = await readFile(oxlintDtsPath, "utf8");
const dummyRuleMapBody = /interface DummyRuleMap \{([\s\S]*?)\n\}/.exec(oxlintDts)?.[1] ?? "";
const knownRules = new Set<string>();
for (const line of dummyRuleMapBody.split("\n")) {
  const match = /^\s*(?:"([^"]+)"|([a-zA-Z_$][\w$-]*))\?:/.exec(line);
  const name = match?.[1] ?? match?.[2];
  if (name !== undefined && name !== "") {
    knownRules.add(name);
  }
}

const filteredRecommended: RuleMap = {};
const skipped: string[] = [];
for (const [name, value] of Object.entries(recommended)) {
  if (knownRules.has(name)) {
    filteredRecommended[name] = value;
  } else {
    skipped.push(name);
  }
}

const sortedKeys = Object.keys(filteredRecommended).toSorted();
const sortedRecommended: RuleMap = {};
for (const key of sortedKeys) {
  sortedRecommended[key] = filteredRecommended[key];
}

const banner = "// AUTO-GENERATED by scripts/generate.ts — do not edit.";

const recommendedFile = `${banner}
import type { OxlintConfig } from "oxlint";

export const recommended = ${JSON.stringify(sortedRecommended, undefined, 2)} satisfies OxlintConfig["rules"];
`;

await mkdir(outDir, { recursive: true });
await writeFile(path.resolve(outDir, "recommended.generated.ts"), recommendedFile, "utf8");

const rawDts = await pluginsToRulesDTS(
  {
    import: importPlugin,
    jsdoc: jsdocPlugin,
    promise: promise as never,
    typescript: tseslint as never,
    unicorn: unicorn,
    vitest: vitest,
  },
  {
    exportTypeName: "RuleOptions",
    includeAugmentation: false,
    includeIgnoreComments: true,
    includeTypeImports: true,
  },
);

const linterShim = `type RuleSeverity = "error" | "warn" | "off" | 0 | 1 | 2;
declare namespace Linter {
  export type RuleEntry<Options extends readonly unknown[] = []> =
    | RuleSeverity
    | [RuleSeverity, ...Options];
}
`;

const dts = rawDts.replace(/^import type \{ Linter \} from ['"]eslint['"]\n?/m, linterShim);

await writeFile(
  path.resolve(outDir, "rules.generated.ts"),
  `${banner}\n// @ts-nocheck\n${dts}`,
  "utf8",
);

// Format the just-written files with the project's oxfmt config so the output
// matches the committed (formatted) files and `pnpm build` stays idempotent.
execFileSync(
  "oxfmt",
  [path.resolve(outDir, "recommended.generated.ts"), path.resolve(outDir, "rules.generated.ts")],
  { stdio: "inherit" },
);

console.log(`✔ wrote recommended.generated.ts (${String(sortedKeys.length)} rules)`);
console.log(`✔ wrote rules.generated.ts`);
console.log(`  skipped ${String(skipped.length)} rules not implemented by oxlint`);
